name: Coana Vulnerability Analysis

on:
  schedule:
    - cron: '0 3 * * *' # every day at 3 AM
  workflow_dispatch: # run manually

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  coana-vulnerability-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable corepack for Node
        run: corepack enable

      - name: Use Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'npm'

      - run: npm ci

      - name: Run Coana CLI
        id: coana-cli
        uses: coana-tech/coana-action/vulnerability-analysis@stable
        with:
          apiKey: ${{ secrets.COANA_API_KEY_PUBLIC_REPOS }}
          repoUrl: https://github.com/${{github.repository}}
          debug: 'true'
          uploadReportArtifact: 'true'
