name: pull

on:
  pull_request:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - run: npm ci
      - run: npm test
      - run: npm run test:e2e
      - name: Upload e2e test artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-test-artifact
          path: |
            .test-artifacts/**/.serverless/*.json
            .test-artifacts/**/.serverless/*.zip
          retention-days: 7
      - run: npm run build --if-present
